### ISSUE TITLE
theoretical question

### ISSUE THREAD

**Issue by hlsafin** [younggyoseo/RE3#5]
How does this deal with games like Montezuma's revenge? Is the reward too sparse, maybe?
Thank you

**Comment by younggyoseo** [comment]
Hi, I just noticed this question. We have some preliminary results on Atari in Figure 13 (also Montezuma's Revenge on Figure 13(a)) which hints that our method can also work for Montezuma's Revenge. While we could not run more to see the trends over longer timesteps, I guess our method might need a sufficiently large-size replay buffer to be consistent over ~200m timesteps because intrinsic rewards are computed based on the distances to the samples in the replay buffer.
